//! Modal windows: Tools > Libraries, Tools > Settings, Help > About and the
//! confirmation shown by File > Quit.

use eframe::egui::{self, RichText};

use crate::panels::MIN_KEY_WIDTH;

/// Product name, as shown in the title bar and in About.
pub const PRODUCT: &str = "bit-music gui-player";
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub const LICENSE: &str = "MIT OR Apache-2.0";

/// Generated by `build.rs` from `Cargo.lock`: `INTERNAL` and `THIRD_PARTY`,
/// each a list of `(name, version)`.
mod libraries {
    include!(concat!(env!("OUT_DIR"), "/libraries.rs"));
}
pub use libraries::{INTERNAL, THIRD_PARTY};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Dialog {
    Libraries,
    Settings,
    About,
    ConfirmQuit,
}

impl Dialog {
    fn title(self) -> &'static str {
        match self {
            Dialog::Libraries => "Libraries",
            Dialog::Settings => "Settings",
            Dialog::About => "About",
            Dialog::ConfirmQuit => "Quit",
        }
    }
}

/// Shows the open dialog (if any) as a modal; clears it when the user
/// closes it (Close button, Esc or a click outside). Returns `true` when
/// the user confirmed quitting.
pub fn show(ctx: &egui::Context, open: &mut Option<Dialog>) -> bool {
    let Some(dialog) = *open else { return false };
    let mut close = false;
    let mut quit = false;
    // One id per dialog: egui remembers a window's size by id, and sharing
    // one would make a small dialog reopen as big as the largest one.
    let modal = egui::Modal::new(egui::Id::new(("app_dialog", dialog))).show(ctx, |ui| {
        ui.set_width(400.0);
        ui.heading(dialog.title());
        ui.separator();
        match dialog {
            Dialog::Libraries => libraries_body(ui),
            Dialog::Settings => {
                ui.label(RichText::new("There are no settings yet.").weak());
            }
            Dialog::About => about_body(ui),
            Dialog::ConfirmQuit => {
                ui.label("Do you want to quit bit-music gui-player?");
            }
        }
        ui.add_space(8.0);
        // Action buttons always sit at the bottom right (right-to-left:
        // the first one added is the rightmost).
        ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
            if dialog == Dialog::ConfirmQuit {
                if ui.button("Cancel").clicked() {
                    close = true;
                }
                if ui.button("Quit").clicked() {
                    quit = true;
                }
            } else if ui.button("Close").clicked() {
                close = true;
            }
        });
    });
    if quit || close || modal.should_close() {
        *open = None;
    }
    quit
}

/// A name / version table that fills the whole width of the window.
fn version_table(ui: &mut egui::Ui, id: &str, libs: &[(&str, &str)]) {
    const GAP: f32 = 16.0;
    let column = ((ui.available_width() - GAP) / 2.0).floor();
    egui::Grid::new(id)
        .num_columns(2)
        .min_col_width(column)
        .spacing([GAP, 4.0])
        .striped(true)
        .show(ui, |ui| {
            for (name, version) in libs {
                ui.label(*name);
                ui.label(RichText::new(format!("v{version}")).monospace());
                ui.end_row();
            }
        });
}

fn libraries_body(ui: &mut egui::Ui) {
    egui::ScrollArea::vertical()
        .max_height(360.0)
        .auto_shrink([true, true])
        .show(ui, |ui| {
            ui.label(RichText::new("bit-music libraries").strong());
            version_table(ui, "internal_libs", INTERNAL);
            ui.add_space(8.0);
            ui.label(RichText::new("Third-party libraries (direct dependencies)").strong());
            version_table(ui, "third_party_libs", THIRD_PARTY);
        });
}

fn about_body(ui: &mut egui::Ui) {
    egui::Grid::new("about_grid")
        .num_columns(2)
        .min_col_width(MIN_KEY_WIDTH)
        .spacing([16.0, 4.0])
        .show(ui, |ui| {
            ui.label(RichText::new("Product").weak());
            ui.label(PRODUCT);
            ui.end_row();
            ui.label(RichText::new("Version").weak());
            ui.label(format!("v{VERSION}"));
            ui.end_row();
            ui.label(RichText::new("License").weak());
            ui.label(LICENSE);
            ui.end_row();
        });
    ui.add_space(6.0);
    ui.label(
        RichText::new(
            "The licenses of the third-party libraries it is built with are \
             listed in THIRD_PARTY_LICENSES.md.",
        )
        .weak(),
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_library_lists_carry_versions() {
        assert!(INTERNAL.iter().any(|(n, _)| *n == "bm-playback"));
        assert!(THIRD_PARTY.iter().any(|(n, _)| *n == "eframe"));
        for (name, version) in INTERNAL.iter().chain(THIRD_PARTY) {
            assert!(
                version.split('.').count() >= 3 && version.chars().next().unwrap().is_ascii_digit(),
                "{name} has no proper version: {version}"
            );
        }
        // Internal libraries carry their own version, not a shared one.
        let playback = INTERNAL.iter().find(|(n, _)| *n == "bm-playback").unwrap();
        assert_eq!(playback.1, "0.2.0");
    }

    #[test]
    fn every_dialog_draws() {
        for d in [Dialog::Libraries, Dialog::Settings, Dialog::About, Dialog::ConfirmQuit] {
            let mut open = Some(d);
            egui::__run_test_ctx(|ctx| assert!(!show(ctx, &mut open)));
            assert_eq!(open, Some(d));
        }
    }
}
