//! Modal windows: Tools > Libraries, Tools > Settings, Help > About and the
//! confirmation shown by File > Quit.

use eframe::egui::{self, RichText};
use egui_phosphor::regular;
use serde_json::Value;

use crate::config::{self, Config, ControlType, SettingDef};
use crate::errors::{self, ErrorLog};
use crate::i18n::{self, t, tf};
use crate::panels::{ERR_COLOR, MIN_KEY_WIDTH};
use crate::widgets::IconButton;

/// Product name, as shown in the title bar and in About.
pub const PRODUCT: &str = "bit-music gui-player";
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub const LICENSE: &str = "MIT OR Apache-2.0";

/// Generated by `build.rs` from `Cargo.lock`: `INTERNAL` and `THIRD_PARTY`,
/// each a list of `(name, version)`.
mod libraries {
    include!(concat!(env!("OUT_DIR"), "/libraries.rs"));
}
pub use libraries::{INTERNAL, THIRD_PARTY};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Dialog {
    Libraries,
    Settings,
    About,
    ConfirmQuit,
    /// A message about the result of an operation (its text is passed to
    /// `show`).
    Notice,
    /// The list of errors (the log).
    Errors,
}

impl Dialog {
    fn title(self) -> &'static str {
        match self {
            Dialog::Libraries => t("dlg.libraries"),
            Dialog::Settings => t("dlg.settings"),
            Dialog::About => t("dlg.about"),
            Dialog::ConfirmQuit => t("dlg.quit"),
            Dialog::Notice => t("dlg.export"),
            Dialog::Errors => t("dlg.errors"),
        }
    }
}

/// What closing the open dialog produced.
#[derive(Debug, Default)]
pub struct Outcome {
    /// The user confirmed quitting.
    pub quit: bool,
    /// The user accepted (OK) the edited configuration of Tools > Settings.
    pub settings: Option<Config>,
    /// The area the dialog took on screen this frame (for tests).
    pub area: Option<egui::Rect>,
}

/// Shows the open dialog (if any) as a modal; clears it when the user
/// closes it (its buttons, Esc or a click outside). `draft` is the copy of
/// the configuration being edited while Settings is open; it is handed back
/// in the outcome on OK and dropped otherwise.
///
/// `notice` is the text of a [`Dialog::Notice`].
pub fn show(
    ctx: &egui::Context,
    open: &mut Option<Dialog>,
    draft: &mut Option<Config>,
    notice: &str,
    errors: &mut ErrorLog,
) -> Outcome {
    let Some(dialog) = *open else { return Outcome::default() };
    let mut close = false;
    let mut outcome = Outcome::default();
    // One id per dialog: egui remembers a window's size by id, and sharing
    // one would make a small dialog reopen as big as the largest one.
    let modal = egui::Modal::new(egui::Id::new(("app_dialog", dialog))).show(ctx, |ui| {
        ui.set_width(match dialog {
            Dialog::Settings => 720.0,
            Dialog::Errors => 820.0,
            _ => 400.0,
        });
        ui.heading(dialog.title());
        ui.separator();
        match dialog {
            Dialog::Libraries => libraries_body(ui),
            Dialog::Settings => {
                if let Some(draft) = draft.as_mut() {
                    settings_body(ui, draft);
                }
            }
            Dialog::About => about_body(ui),
            Dialog::ConfirmQuit => {
                ui.label(t("dlg.quit_question"));
            }
            Dialog::Notice => {
                ui.add(egui::Label::new(notice).wrap());
            }
            Dialog::Errors => errors_body(ui, errors),
        }
        // A horizontal line separates the content from the button bar.
        ui.add_space(4.0);
        ui.separator();
        // Action buttons always sit at the bottom right (right-to-left:
        // the first one added is the rightmost).
        match dialog {
            Dialog::ConfirmQuit => {
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    if ui.button(t("btn.cancel")).clicked() {
                        close = true;
                    }
                    if ui.button(t("btn.quit")).clicked() {
                        outcome.quit = true;
                    }
                });
            }
            Dialog::Settings => {
                ui.horizontal(|ui| {
                    if ui.button(t("btn.reset_all")).clicked() {
                        if let Some(draft) = draft.as_mut() {
                            draft.reset_user_settings();
                        }
                    }
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if ui.button(t("btn.cancel")).clicked() {
                            close = true;
                        }
                        if ui.button(t("btn.ok")).clicked() {
                            outcome.settings = draft.take();
                            close = true;
                        }
                    });
                });
            }
            Dialog::Errors => {
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    if ui.button(t("btn.close")).clicked() {
                        close = true;
                    }
                    if ui
                        .add_enabled(!errors.is_empty(), egui::Button::new(t("btn.clear_all")))
                        .clicked()
                    {
                        errors.clear();
                    }
                });
            }
            _ => {
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    if ui.button(t("btn.close")).clicked() {
                        close = true;
                    }
                });
            }
        }
    });
    outcome.area = Some(modal.response.rect);
    if outcome.quit || close || modal.should_close() {
        *open = None;
        *draft = None;
    }
    outcome
}

/// The body of the errors window: the stack of errors, newest first, each
/// as an element with its time, its text (over as many lines as it needs) and
/// a button that removes it. Scrolls vertically.
fn errors_body(ui: &mut egui::Ui, errors: &mut ErrorLog) {
    let mut remove = None;
    // The list has a fixed size, however many errors there are: the window
    // does not change when they are removed.
    let height = ERRORS_LIST_HEIGHT.min(ui.ctx().content_rect().height() * 0.7);
    egui::ScrollArea::vertical()
        .min_scrolled_height(height)
        .max_height(height)
        .auto_shrink([false, false])
        .show(ui, |ui| {
            if errors.is_empty() {
                ui.label(RichText::new(t("errors.none")).weak());
                return;
            }
            // A row per error, as a card: a soft background, no lines. One
            // width for all of them, worked out once (measuring it for each
            // would let them grow, one after the other).
            let card = egui::Frame::new()
                .fill(ui.visuals().widgets.inactive.weak_bg_fill.gamma_multiply(0.55))
                .corner_radius(4.0)
                .inner_margin(8.0);
            let inner_width = ui.available_width() - card.total_margin().sum().x;
            for entry in errors.entries() {
                card.show(ui, |ui| {
                    ui.set_width(inner_width);
                    if error_row(ui, entry) {
                        remove = Some(entry.id);
                    }
                });
            }
        });
    if let Some(id) = remove {
        errors.remove(id);
    }
}

/// Height of the errors list, in points.
const ERRORS_LIST_HEIGHT: f32 = 460.0;

/// One error as a single row: the time over the text on the left, and the
/// remove button at the right, centered vertically on the whole row.
/// Returns whether the button was clicked.
fn error_row(ui: &mut egui::Ui, entry: &errors::ErrorEntry) -> bool {
    let mut remove = false;
    // Aligned to the top: a centered row would start below the card's top
    // margin (the text block is created with no height yet), leaving more
    // room above the time than below the text.
    ui.horizontal_top(|ui| {
        let button = ui.spacing().interact_size.y + 8.0;
        let cell = button + 20.0;
        let text_width = (ui.available_width() - cell - ui.spacing().item_spacing.x).max(40.0);

        let text = ui.allocate_ui_with_layout(
            egui::vec2(text_width, 0.0),
            egui::Layout::top_down(egui::Align::Min),
            |ui| {
                ui.set_min_width(text_width);
                ui.label(RichText::new(errors::format_time(entry.time)).weak().small());
                ui.add(egui::Label::new(RichText::new(&entry.text).color(ERR_COLOR)).wrap());
            },
        );

        // The button goes exactly at the middle of the text block (the time
        // and the text together), in the middle of its cell at the right.
        let block = text.response.rect;
        let center = egui::pos2(
            block.right() + ui.spacing().item_spacing.x + cell / 2.0,
            block.center().y,
        );
        remove = ui
            .put(
                egui::Rect::from_center_size(center, egui::Vec2::splat(button)),
                IconButton::new(regular::X_CIRCLE).size(button),
            )
            .on_hover_text(t("errors.remove"))
            .clicked();
    });
    remove
}

/// The body of Tools > Settings, built from the schema: one row per
/// user-editable setting, with the control its `controlType` asks for and a
/// button to restore its default.
fn settings_body(ui: &mut egui::Ui, draft: &mut Config) {
    egui::Grid::new("settings_grid")
        .num_columns(3)
        .spacing([16.0, 8.0])
        .show(ui, |ui| {
            for def in config::user_definitions() {
                ui.vertical(|ui| {
                    ui.set_width(240.0);
                    ui.label(setting_text(&def.key, "title", &def.title));
                    let description = setting_text(&def.key, "description", &def.description);
                    if !description.is_empty() {
                        ui.label(RichText::new(description).weak().small());
                    }
                });
                setting_control(ui, def, draft);
                let changed = def.default.is_some() && draft.value(&def.key) != def.default;
                // Square like the control next to it, as tall as the control.
                let side = ui.spacing().interact_size.y;
                let restore = ui
                    .add_enabled(changed, IconButton::new(regular::ARROW_COUNTER_CLOCKWISE).size(side))
                    .on_hover_text(t("btn.restore_default"));
                if restore.clicked() {
                    if let Some(default) = &def.default {
                        draft.set(&def.key, default.clone());
                    }
                }
                ui.end_row();

                // The history goes right under the setting for its size.
                if def.key == config::MAX_LAST_OPENED {
                    history_row(ui, draft);
                }
            }
        });
}

/// `Recent files | N in the history [Clear history]`.
fn history_row(ui: &mut egui::Ui, draft: &mut Config) {
    ui.label(t("settings.recent_files"));
    ui.horizontal(|ui| {
        ui.label(
            RichText::new(tf("settings.history_count", &[("count", &draft.last_opened.len().to_string())])).weak(),
        );
        if ui
            .add_enabled(!draft.last_opened.is_empty(), egui::Button::new(t("btn.clear_history")))
            .clicked()
        {
            draft.last_opened.clear();
        }
    });
    ui.label(""); // nothing to restore here
    ui.end_row();
}

/// Width of the control that holds a setting's value, in points.
const CONTROL_WIDTH: f32 = 400.0;

/// A setting's title or description in the current language, falling back to
/// the text in the schema.
fn setting_text(key: &str, what: &str, fallback: &str) -> String {
    i18n::lookup(&format!("setting.{key}.{what}"))
        .map_or_else(|| fallback.to_string(), str::to_string)
}

/// The text of one choice of a combo: translated if there is a text for it
/// (`value.<setting>.<choice>`), the value itself otherwise.
fn choice_label(key: &str, choice: &Value) -> String {
    let raw = match choice {
        Value::String(s) => s.clone(),
        other => other.to_string(),
    };
    i18n::lookup(&format!("value.{key}.{raw}"))
        .map_or(raw, str::to_string)
}

/// The editing widget of one setting, according to its control type.
fn setting_control(ui: &mut egui::Ui, def: &SettingDef, draft: &mut Config) {
    let current = draft.value(&def.key);
    let range = def.min.unwrap_or(i64::MIN)..=def.max.unwrap_or(i64::MAX);
    match (def.control_type, current) {
        (Some(ControlType::Spinner), Some(Value::Number(n))) => {
            let mut v = n.as_i64().unwrap_or_default();
            ui.spacing_mut().slider_width = CONTROL_WIDTH - 60.0;
            if ui.add(egui::DragValue::new(&mut v).range(range)).changed() {
                draft.set(&def.key, Value::from(v));
            }
        }
        (Some(ControlType::Slider), Some(Value::Number(n))) => {
            let mut v = n.as_i64().unwrap_or_default();
            if ui.add(egui::Slider::new(&mut v, range)).changed() {
                draft.set(&def.key, Value::from(v));
            }
        }
        (Some(ControlType::Checkbox), Some(Value::Bool(mut b))) => {
            if ui.checkbox(&mut b, "").changed() {
                draft.set(&def.key, Value::Bool(b));
            }
        }
        (Some(ControlType::Input), Some(Value::String(mut text))) => {
            if ui
                .add(egui::TextEdit::singleline(&mut text).desired_width(CONTROL_WIDTH))
                .changed()
            {
                draft.set(&def.key, Value::String(text));
            }
        }
        (Some(ControlType::Combo), Some(selected)) => {
            egui::ComboBox::from_id_salt(&def.key)
                .width(CONTROL_WIDTH)
                .selected_text(choice_label(&def.key, &selected))
                .show_ui(ui, |ui| {
                    for choice in &def.choices {
                        let label = choice_label(&def.key, choice);
                        if ui.selectable_label(*choice == selected, label).clicked() {
                            draft.set(&def.key, choice.clone());
                        }
                    }
                });
        }
        _ => {
            ui.label(RichText::new(t("settings.unavailable")).weak());
        }
    }
}

/// A name / version table that fills the whole width of the window.
fn version_table(ui: &mut egui::Ui, id: &str, libs: &[(&str, &str)]) {
    const GAP: f32 = 16.0;
    let column = ((ui.available_width() - GAP) / 2.0).floor();
    egui::Grid::new(id)
        .num_columns(2)
        .min_col_width(column)
        .spacing([GAP, 4.0])
        .striped(true)
        .show(ui, |ui| {
            for (name, version) in libs {
                ui.label(*name);
                ui.label(RichText::new(format!("v{version}")).monospace());
                ui.end_row();
            }
        });
}

fn libraries_body(ui: &mut egui::Ui) {
    egui::ScrollArea::vertical()
        .max_height(360.0)
        .auto_shrink([true, true])
        .show(ui, |ui| {
            ui.label(RichText::new(t("libs.internal")).strong());
            version_table(ui, "internal_libs", INTERNAL);
            ui.add_space(8.0);
            ui.label(RichText::new(t("libs.third_party")).strong());
            version_table(ui, "third_party_libs", THIRD_PARTY);
        });
}

fn about_body(ui: &mut egui::Ui) {
    egui::Grid::new("about_grid")
        .num_columns(2)
        .min_col_width(MIN_KEY_WIDTH)
        .spacing([16.0, 4.0])
        .show(ui, |ui| {
            ui.label(RichText::new(t("about.product")).weak());
            ui.label(PRODUCT);
            ui.end_row();
            ui.label(RichText::new(t("about.version")).weak());
            ui.label(format!("v{VERSION}"));
            ui.end_row();
            ui.label(RichText::new(t("about.license")).weak());
            ui.label(LICENSE);
            ui.end_row();
        });
    ui.add_space(6.0);
    ui.label(RichText::new(t("about.third_party_note")).weak());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_library_lists_carry_versions() {
        assert!(INTERNAL.iter().any(|(n, _)| *n == "bm-playback"));
        assert!(THIRD_PARTY.iter().any(|(n, _)| *n == "eframe"));
        for (name, version) in INTERNAL.iter().chain(THIRD_PARTY) {
            assert!(
                version.split('.').count() >= 3 && version.chars().next().unwrap().is_ascii_digit(),
                "{name} has no proper version: {version}"
            );
        }
        // Internal libraries carry their own version, not a shared one.
        let playback = INTERNAL.iter().find(|(n, _)| *n == "bm-playback").unwrap();
        assert_eq!(playback.1, "0.4.0");
    }

    #[test]
    fn every_dialog_draws() {
        for d in [
            Dialog::Libraries,
            Dialog::Settings,
            Dialog::About,
            Dialog::ConfirmQuit,
            Dialog::Notice,
            Dialog::Errors,
        ] {
            let mut open = Some(d);
            let mut draft = Some(Config::default().with_defaults());
            let mut errors = ErrorLog::default();
            errors.push("something went wrong\nover two lines");
            egui::__run_test_ctx(|ctx| assert!(!show(ctx, &mut open, &mut draft, "done", &mut errors).quit));
            assert_eq!(open, Some(d));
        }
    }

    #[test]
    fn every_user_setting_is_translated_in_every_language() {
        for lang in i18n::Lang::ALL {
            i18n::set_language(lang);
            for def in config::user_definitions() {
                for what in ["title", "description"] {
                    let key = format!("setting.{}.{what}", def.key);
                    assert!(i18n::lookup(&key).is_some(), "{lang:?}: missing {key}");
                }
                // Choices that are words (not numbers) have a label of their own.
                for choice in def.choices.iter().filter_map(Value::as_str) {
                    let key = format!("value.{}.{choice}", def.key);
                    assert!(i18n::lookup(&key).is_some(), "{lang:?}: missing {key}");
                }
            }
        }
        i18n::set_language(i18n::Lang::English);
    }

    #[test]
    fn the_errors_window_keeps_its_size_however_many_errors_there_are() {
        let size_with = |count: usize| {
            let mut errors = ErrorLog::default();
            for n in 0..count {
                errors.push(format!("error number {n}, with a text long enough to need a few words"));
            }
            let mut open = Some(Dialog::Errors);
            let mut draft = None;
            let mut size = None;
            egui::__run_test_ctx(|ctx| {
                // A few frames so the layout settles.
                for _ in 0..3 {
                    let outcome = show(ctx, &mut open, &mut draft, "", &mut errors);
                    size = outcome.area.map(|a| a.size());
                }
            });
            size.unwrap()
        };
        let many = size_with(12);
        assert_eq!(size_with(0), many);
        assert_eq!(size_with(1), many);
        assert_eq!(size_with(3), many);
    }

    #[test]
    fn choices_show_their_translation_or_the_value() {
        assert_eq!(choice_label("lang", &Value::from("SPANISH")), "Español");
        assert_eq!(choice_label("maxLastOpened", &Value::from(15)), "15");
    }
}
