#!/usr/bin/env python3
"""Generates THIRD_PARTY_LICENSES.md: the license notices of every third-party
crate that ends up in the Windows and Linux binaries.

Usage (from the repository root, after `cargo fetch`/a build):

    python3 scripts/gen-third-party-licenses.py

It reads the resolved dependency graph for the two supported targets with
`cargo metadata`, collects each crate's license files (LICENSE*, COPYING*,
NOTICE*, and the font licenses under `fonts/`), and writes them deduplicated:
identical texts appear once, followed by the crates they apply to.
"""
import collections
import json
import pathlib
import re
import subprocess
import sys

TARGETS = ["x86_64-pc-windows-gnu", "x86_64-unknown-linux-gnu"]
OUTPUT = pathlib.Path("THIRD_PARTY_LICENSES.md")
NAME_RE = re.compile(r"^(licen[cs]e|copying|unlicense|notice|copyright|ofl|ufl)", re.I)
# Subdirectories where some crates keep license texts.
EXTRA_DIRS = ["licenses", "LICENSES", "license", "fonts"]


def resolved_packages():
    found = {}
    for target in TARGETS:
        out = subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--filter-platform", target, "--locked"],
            capture_output=True, text=True, check=True,
        ).stdout
        data = json.loads(out)
        ids = {n["id"] for n in data["resolve"]["nodes"]}
        for p in data["packages"]:
            if p["id"] in ids and p["source"] is not None:  # third-party only
                found[(p["name"], p["version"])] = p
    return found


def license_files(package):
    root = pathlib.Path(package["manifest_path"]).parent
    files = [f for f in sorted(root.iterdir()) if f.is_file() and NAME_RE.match(f.name)]
    for extra in EXTRA_DIRS:
        d = root / extra
        if d.is_dir():
            files += [
                f for f in sorted(d.iterdir())
                if f.is_file() and f.suffix.lower() in ("", ".txt", ".md")
                and (NAME_RE.match(f.name) or "licen" in f.name.lower() or extra == "fonts")
            ]
    return files


def main():
    packages = resolved_packages()
    by_text = collections.OrderedDict()   # text -> list of "name version"
    no_text = []                           # crates that ship no license file
    for (name, version), p in sorted(packages.items()):
        texts = []
        for f in license_files(p):
            try:
                text = f.read_text(encoding="utf-8", errors="replace").strip()
            except OSError:
                continue
            if text:
                texts.append(text)
        if not texts:
            no_text.append((name, version, p.get("license")))
        for text in dict.fromkeys(texts):  # de-duplicate within the crate
            by_text.setdefault(text, []).append(f"{name} {version}")

    lines = [
        "# Third-party licenses",
        "",
        "bit-music is licensed under `MIT OR Apache-2.0` (see the repository README).",
        "It is built on the third-party components below, each under its own license.",
        "",
        "This file is generated by `scripts/gen-third-party-licenses.py` from `Cargo.lock`",
        "for the `x86_64-pc-windows-gnu` and `x86_64-unknown-linux-gnu` targets. Do not edit it by hand.",
        "",
        f"## Components ({len(packages)})",
        "",
        "| Crate | Version | License |",
        "|---|---|---|",
    ]
    for (name, version), p in sorted(packages.items()):
        lines.append(f"| {name} | {version} | {p.get('license') or 'see license text'} |")

    if no_text:
        lines += ["", "## Components whose crate does not ship a license text", "",
                  "These declare their license in `Cargo.toml` only; see the SPDX identifier:", ""]
        for name, version, lic in no_text:
            lines.append(f"- {name} {version}: {lic or 'unspecified'}")

    lines += ["", "## License texts", ""]
    for i, (text, users) in enumerate(by_text.items(), 1):
        lines += [f"### {i}. Applies to: {', '.join(users)}", "", "```text", text, "```", ""]

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUTPUT}: {len(packages)} components, {len(by_text)} distinct license texts, "
          f"{len(no_text)} without a shipped text, {OUTPUT.stat().st_size // 1024} KiB")


if __name__ == "__main__":
    sys.exit(main())
